# Generated by Django 4.1.4 on 2023-06-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
                ('Subcategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.BigIntegerField()),
            ],
        ),
    ]
